### PR TITLE
Refactor #1

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
This is first commit and it refactors the entire code. These are the
changes and reasons for those changes:

1. model.py is a seperate file to manage all the things related to model
   eventually will need to put Processing as a seperate file as well
2. utils.py a file to include all the functional utilities that make life
   easier
3. more tests and correct the existing ones

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
@yashbonde for the 1st point, let's separate preprocesssing right now.

**Comment by Aakash-kaushik** [comment]
Also moving the assests folder inside test. basically test realted everything inside test.

**Comment by yashbonde** [comment]
makes, sense. I'll work on it from the evening.

**Comment by Aakash-kaushik** [comment]
i already made the above two changes, will merge the PR in a bit after taking a complete look.

**Comment by Aakash-kaushik** [comment]
I believe the TF loading is happening because of transformers: 
image

Change: transformers shouldn't even be loaded unless someone loads an NLP model ?

**Comment by yashbonde** [comment]
we need to implement checking and conditionals and it'll manage everything. In `transformers` pytorch is checked then tensorflow, so tf does all thise.

**Comment by Aakash-kaushik** [comment]
> we need to implement checking and conditionals and it'll manage everything. In `transformers` pytorch is checked then tensorflow, so tf does all this.

yup, what we did for torchvision, let's do the same thing for transformers ?, when you call for an nlp model that's when it's loaded, we don't need actual libs to just match the keys in the dict which are basically strings. 

I will merge this for now so i can continue working and then will add that.

**Pull request merged**
